#!/bin/bash
ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
chmod 600 /root/.ssh/authorized_keys
curl -L https://github.com/usrbinkat.keys | tee -a ~/.ssh/authorized_keys
dnf update -y && dnf install openssh-server ansible python -y
systemctl unmask systemd-logind
systemctl enable --now sshd

cat <<EOF >/root/.bashrc
# .bashrc
# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
# Uncomment the following line if you don't like systemctl's auto-paging feature:
    # using tput commands
    FGBLK=$( tput setaf 0 ) # 000000
    FGRED=$( tput setaf 1 ) # ff0000
    FGGRN=$( tput setaf 2 ) # 00ff00
    FGYLO=$( tput setaf 3 ) # ffff00
    FGBLU=$( tput setaf 4 ) # 0000ff
    FGMAG=$( tput setaf 5 ) # ff00ff
    FGCYN=$( tput setaf 6 ) # 00ffff
    FGWHT=$( tput setaf 7 ) # ffffff
    BGBLK=$( tput setab 0 ) # 000000
    BGRED=$( tput setab 1 ) # ff0000
    BGGRN=$( tput setab 2 ) # 00ff00
    BGYLO=$( tput setab 3 ) # ffff00
    BGBLU=$( tput setab 4 ) # 0000ff
    BGMAG=$( tput setab 5 ) # ff00ff
    BGCYN=$( tput setab 6 ) # 00ffff
    BGWHT=$( tput setab 7 ) # ffffff
    RESET=$( tput sgr0 )
    BOLDM=$( tput bold )
    UNDER=$( tput smul )
    REVRS=$( tput rev )
if [ $EUID == 0 ]; then
  export PS1="\[$FGRED\]\u\[$FGMAG\]@\[$FGCYN\]\h \[$FGBLU\]\W\$ \[$RESET\]"
 else
  export PS1="\[$FGGRN\]\u\[$FGMAG\]@\[$FGCYN\]\h \[$FGBLU\]\W\$ \[$RESET\]"
fi
# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Custom alias(es)
alias ibane='ssh ibane'
alias gateway='ssh gateway'
alias cloudctl='ssh cloudctl'
alias haproxy='ssh haproxy'
alias nfs='ssh nfs'
alias dnsmasq='ssh dnsmasq'
alias tftp='ssh tftp'
alias httpd='ssh httpd'
alias simpleca='ssh simpleca'
alias squid='ssh squid'
alias ipa='ssh ipa'
alias bootstrap='ssh bootstrap'
alias master01='ssh master0'
alias master02='ssh master1'
alias master03='ssh master2'
alias worker01='ssh worker00'
alias worker02='ssh worker01'
alias worker03='ssh worker02'
EOF
